all:
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: plaintext
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    # Default credentials on gusztavvargadr boxes (WinRM is already
    # configured in plaintext, no need for our own ConfigureRemotingForAnsible).
    ansible_user: vagrant
    ansible_password: vagrant

  children:
    dc:
      hosts:
        hokage-dc01:
          ansible_host: 192.168.56.10

    members:
      hosts:
        anbu-srv01:
          ansible_host: 192.168.56.11
        mission-srv01:
          ansible_host: 192.168.56.12

    workstations:
      hosts:
        academy-ws01:
          ansible_host: 192.168.56.13

    domain_joined:
      children:
        members:
        workstations:
